name: babybip39
description: Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
version: 1.0.4
homepage: https://github.com/lpreimesberger/bip39

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  pointycastle: ^3.3.4
  hex: ^0.2.0
  crypto: ^3.0.1
dev_dependencies:
  test: ^1.0.0
