name: babybip39
description: Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
version: 1.0.4
homepage: https://github.com/lpreimesberger/bip39

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  pointycastle: ^2.0.0
  hex: ^0.1.2
  crypto: ^2.0.3
dev_dependencies:
  test: ^1.0.0
